// This file provides a client with methods as well as functions to interact with the HTTP API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package gamerpower

import (
	"context"
	"encoding/json/v2"
	"net/http"
	"net/url"
	"strings"

	"github.com/go-api-libs/api"
)

const defaultUserAgent = "Free Games API"

var defaultBaseURL = &url.URL{
	Scheme: "http",
	Host:   "www.gamerpower.com",
	Path:   "/api",
}

// Client is an HTTP client for the gamerpower API.
type Client struct {
	// The HTTP client to use for requests.
	cli *http.Client
	// The base URL
	baseURL *url.URL
	// The user agent
	userAgent string
}

// ClientOption configures a [Client].
type ClientOption func(*Client)

// WithBaseURL returns a [ClientOption] that overrides the default base URL.
// It will prefix a leading slash to the path if there is none.
func WithBaseURL(baseURL *url.URL) ClientOption {
	if !strings.HasPrefix(baseURL.Path, "/") {
		baseURL.Path = "/" + baseURL.Path
	}

	return func(c *Client) { c.baseURL = baseURL }
}

// WithHTTPClient returns a [ClientOption] that sets a custom HTTP client.
func WithHTTPClient(cli *http.Client) ClientOption {
	return func(c *Client) { c.cli = cli }
}

// NewClient creates a new Client.
func NewClient(opts ...ClientOption) (*Client, error) {
	c := &Client{
		cli:       http.DefaultClient,
		baseURL:   defaultBaseURL,
		userAgent: defaultUserAgent,
	}

	for _, opt := range opts {
		opt(c)
	}

	return c, nil
}

// Returns all active giveaways.
//
//	GET /giveaways
func (c *Client) ListGiveaways(ctx context.Context) (Giveaways, error) {
	out, err := c.ListGiveawaysWithResult[Giveaways](ctx)
	if err != nil {
		return nil, err
	}

	return *out, nil
}

// Returns all active giveaways.
// You can define a custom result to unmarshal the response into.
//
//	GET /giveaways
func (c *Client) ListGiveawaysWithResult[R any](ctx context.Context) (*R, error) {
	u := c.baseURL.JoinPath("giveaways")
	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}

// Total live giveaways & worth estimation in US dollars.
//
//	GET /worth
func (c *Client) GetWorth(ctx context.Context) (*Worth, error) {
	return c.GetWorthWithResult[Worth](ctx)
}

// Total live giveaways & worth estimation in US dollars.
// You can define a custom result to unmarshal the response into.
//
//	GET /worth
func (c *Client) GetWorthWithResult[R any](ctx context.Context) (*R, error) {
	u := c.baseURL.JoinPath("worth")
	req := (&http.Request{
		Header: http.Header{
			"User-Agent": []string{c.userAgent},
		},
		Host:       u.Host,
		Method:     http.MethodGet,
		Proto:      "HTTP/1.1",
		ProtoMajor: 1,
		ProtoMinor: 1,
		URL:        u,
	}).WithContext(ctx)

	rsp, err := c.cli.Do(req)
	if err != nil {
		return nil, err
	}
	defer rsp.Body.Close()

	switch rsp.StatusCode {
	case http.StatusOK:
		// OK
		switch mt, _, _ := strings.Cut(rsp.Header.Get("Content-Type"), ";"); mt {
		case "application/json":
			var out R
			if err := json.UnmarshalRead(rsp.Body, &out, jsonOpts); err != nil {
				return nil, api.WrapDecodingError(rsp, err)
			}

			return &out, nil
		default:
			return nil, api.NewErrUnknownContentType(rsp)
		}
	default:
		return nil, api.NewErrUnknownStatusCode(rsp)
	}
}
