// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package gamerpower

import (
	"encoding/json/v2"
	"net/url"

	"github.com/MarkRosemaker/jsonutil"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
	json.WithMarshalers(json.JoinMarshalers(
		json.MarshalToFunc(jsonutil.URLMarshal),
	)),
	json.WithUnmarshalers(json.JoinUnmarshalers(
		json.UnmarshalFromFunc(jsonutil.URLUnmarshal),
	)),
)

// ListAPIWorthOk defines a model
type ListAPIWorthOk struct {
	ActiveGiveawaysNumber int    `json:"active_giveaways_number"`
	WorthEstimationUsd    string `json:"worth_estimation_usd,omitzero"`
}

// ListGiveawaysOk defines a model
type ListGiveawaysOk []ListGiveawaysOkItem

// ListGiveawaysOkItem defines a model
type ListGiveawaysOkItem struct {
	ID              int     `json:"id"`
	Title           string  `json:"title,omitzero"`
	Worth           string  `json:"worth,omitzero"`
	Thumbnail       url.URL `json:"thumbnail,omitzero"`
	Image           url.URL `json:"image,omitzero"`
	Description     string  `json:"description,omitzero"`
	Instructions    string  `json:"instructions,omitzero"`
	OpenGiveawayURL url.URL `json:"open_giveaway_url,omitzero"`
	PublishedDate   string  `json:"published_date,omitzero"`
	Type            string  `json:"type,omitzero"`
	Platforms       string  `json:"platforms,omitzero"`
	EndDate         string  `json:"end_date,omitzero"`
	Users           int     `json:"users"`
	Status          string  `json:"status,omitzero"`
	GamerpowerURL   url.URL `json:"gamerpower_url,omitzero"`
	OpenGiveaway    url.URL `json:"open_giveaway,omitzero"`
}
