// This file provides types for the API.
//
// Code generated by MarkRosemaker/openapi-codegen. DO NOT EDIT.

package gamerpower

import (
	"encoding/json/v2"
	"net/url"

	"github.com/MarkRosemaker/jsonutil"
)

var jsonOpts = json.JoinOptions(
	json.RejectUnknownMembers(true),
	json.WithMarshalers(json.JoinMarshalers(
		json.MarshalToFunc(jsonutil.URLMarshal),
	)),
	json.WithUnmarshalers(json.JoinUnmarshalers(
		json.UnmarshalFromFunc(jsonutil.URLUnmarshal),
	)),
)

// Giveaway defines a model
type Giveaway struct {
	ID              int     `json:"id"`
	Title           string  `json:"title"`
	Worth           string  `json:"worth"`
	Thumbnail       url.URL `json:"thumbnail"`
	Image           url.URL `json:"image"`
	Description     string  `json:"description"`
	Instructions    string  `json:"instructions"`
	OpenGiveawayURL url.URL `json:"open_giveaway_url"`
	PublishedDate   string  `json:"published_date"`
	Type            string  `json:"type"`
	Platforms       string  `json:"platforms"`
	EndDate         string  `json:"end_date"`
	Users           int     `json:"users"`
	Status          string  `json:"status"`
	GamerpowerURL   url.URL `json:"gamerpower_url"`
	OpenGiveaway    url.URL `json:"open_giveaway"`
}

// Giveaways defines a model
type Giveaways []Giveaway

// Worth defines a model
type Worth struct {
	ActiveGiveawaysNumber int    `json:"active_giveaways_number"`
	WorthEstimationUsd    string `json:"worth_estimation_usd"`
}
